// Regenerate `src/generated/versions.ts` from package.json files.
// `package.json` is the single source of truth; the generated module is a
// derived artifact (committed so fresh clones typecheck without running gen).
// Usage: `bun run gen`. Re-run whenever a version changes.
export {}

const pkg = (await Bun.file("package.json").json()) as { version?: string }
const effectPkg = (await Bun.file("node_modules/effect/package.json").json()) as {
  version?: string
}

const out = `// Generated by \`bun run gen\`. Do not edit.
export const CLI_VERSION = ${JSON.stringify(pkg.version ?? "0.0.0")} as const
export const EFFECT_VERSION = ${JSON.stringify(effectPkg.version ?? "unknown")} as const
`

if (Bun.argv.includes("--check")) {
  const current = await Bun.file("src/generated/versions.ts").text()
  if (current !== out) {
    console.error("src/generated/versions.ts is stale: run `bun run gen`")
    process.exit(1)
  }
  console.log("versions clean")
  process.exit(0)
}

await Bun.write("src/generated/versions.ts", out)
console.log("wrote src/generated/versions.ts")
