// Embed the agent SKILL into a generated module so `skill show` serves
// the version-matched copy from any binary (no file reads at runtime).
// Usage: `bun ./scripts/gen-skill.ts [--check]`.
export {}

const src = await Bun.file("skills/agent-webmcp/SKILL.md").text()
const out = `// Generated by \`bun run gen:skill\`. Do not edit.
export const SKILL_MD = ${JSON.stringify(src)} as const
`

if (Bun.argv.includes("--check")) {
  const current = await Bun.file("src/generated/skill.ts").text()
  if (current !== out) {
    console.error("src/generated/skill.ts is stale: run `bun run gen:skill`")
    process.exit(1)
  }
  console.log("skill clean")
  process.exit(0)
}

await Bun.write("src/generated/skill.ts", out)
console.log("wrote src/generated/skill.ts")
